server:
  port: 8090
spring:
  datasource:
    url: jdbc:mariadb://mariadb:3306/blog?useSSL=false&serverTimezone=Europe/Zurich&autoReconnect=true&maxReconnects=10&allowPublicKeyRetrieval=true
    username: root
    password: root
  liquibase:
    contexts: seed-blog